FROM alpine:3.21

ARG TARGETPLATFORM
ARG user=app
ARG group=docker
RUN addgroup $group && adduser -D -G $group $user
USER $user

WORKDIR /usr/local/bin
COPY --chown=$user:$group $TARGETPLATFORM/openev-data-mcp /usr/local/bin/openev-data-mcp

CMD ["/usr/local/bin/openev-data-mcp"]