version: "3.9"
services:

  app:
    environment:
      OPENEV_MCP_OBSERVABILITY_ENABLED: "true"
      OPENEV_MCP_OBSERVABILITY_OTLP_ENDPOINT: "lgtm-stack:4317"
    depends_on:
      - grafana-lgtm-stack

  grafana-lgtm-stack:
    image: grafana/otel-lgtm
    container_name: lgtm-stack
    hostname: lgtm-stack
    profiles:
      - observability
    labels:
      - traefik.enable=true
      - traefik.tags=public
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME:-localhost}`)
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.routers.grafana.entrypoints=http
    environment:
      - GF_LOG_LEVEL="debug"
    volumes:
      - prometheus:/prometheus
      - loki:/data/loki
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command:
      - "-config.file=/etc/promtail/promtail.yaml"
    profiles:
      - observability
    hostname: promtail
    restart: always
    depends_on:
      - grafana-lgtm-stack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prometheus:
  grafana:
  loki:
