name: Lint
on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '.run/**'
      - '.vscode/**'
      - 'config/**'
    branches:
      - main
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout 2m